session_name: trim
windows:
- focus: 'true'
  layout: 8a06,348x38,0,0{174x38,0,0,8,173x38,175,0,10}
  options:
    automatic-rename: 'off'
  panes:
  - shell_command:
      - texas
      - clear
  start_directory: /home/trim
  window_name: home
- layout: 8b33,348x38,0,0{69x38,0,0,2,69x38,70,0,3,69x38,140,0,4,69x38,210,0,5,68x38,280,0,6}
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command: 
      - gotoros
      - sourceros
      - clear
  - shell_command: 
      - gotoros
      - sourceros
      - clear
  - shell_command: 
      - gotoros
      - sourceros
      - clear
  - shell_command: 
      - gotoros
      - sourceros
      - clear
  - shell_command: 
      - gotoros
      - sourceros
      - clear
  start_directory: /home/trim
  window_name: ros

